services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${PG_PORT}:${PG_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_logs:/var/log/postgresql
    networks:
      - nestjs_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_app
    image: home-lib:latest
    restart: always
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - nestjs_network

volumes:
  postgres_data:
  postgres_logs:

networks:
  nestjs_network:
    driver: bridge