export enum EventType {
  ALBUM_DELETED = 'ALBUM_DELETED',
  ADD_TRACK_TO_FAVORITES = 'ADD_TRACK_TO_FAVORITES',
  ADD_ARTIST_TO_FAVORITES = 'ADD_ARTIST_TO_FAVORITES',
  ADD_ALBUM_TO_FAVORITES = 'ADD_ALBUM_TO_FAVORITES',
  GET_ENTITY = 'GET_ENTITY',
  ENTITY_DELETED = 'ENTITY_DELETED',
}
